version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    container_name: quelk
    build: .
    command: sbt "~;jetty:stop;jetty:start"
    volumes:
      - ./data/ontologies:/root/data/ontologies
      - .:/root/myapp
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=
      - REWRITER_ONTOLOGY_HOME=/root/data/ontologies
    depends_on:
      - db
      
